### ISSUE TITLE
hello world throwing 'cannot find module workshopper-exercise' error

### ISSUE THREAD

**Issue by scottseeker** [codio/tutorial_nodeschool_expressworks#3]
Hello,

I'm attempting to work through your tutorial but selecting the first exercise 'Hello World' throws an error.

Error: Cannot find module 'workshopper-exercise'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/expressworks/exercises/hello_world/exercise.js:3:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by ghost** [comment]
@scottseeker Sorry but we aren't maintaining these any longer. Many changes have occurred not only with Codio but also with Nodeschool and its probably better you use their tutorial (that I can see was updated very recently as well)

**Comment by scottseeker** [comment]
Thank you for the reply!
